# GainRAG — Gain-Score Reproduction on HotpotQA (Team Shard Run)

**Course:** CSE465..4
**Team member running this notebook:** `EDIT_YOUR_NAME_HERE`

**Purpose:** demonstrate the gain-score calculation (Eq. 4/5) from *GainRAG: Preference
Alignment in Retrieval-Augmented Generation through Gain Signal Synthesis* (Jiang et al.,
2025) using the authors' own unmodified code, run over this teammate's 125-question shard
of the paper's 500-question HotpotQA test set.

**What this notebook does, cell by cell:**
1. Clone the team repo (source + shared datasets)
2. Install dependencies
3. Configure this run (shard file, model backend — local T4 or CraftX API)
4. Load the model (local 4-bit Llama-3-8B, OR CraftX — toggle in Config)
5. Load this teammate's shard
6. Run the gain-calculation loop with checkpointing (safe against Colab disconnects)
7. Display results as a table (for professor demo)
8. Save a small "record" summary (for the writeup / professor demo)
9. Push results back to the team repo

Re-run cells top to bottom at the start of every fresh Colab session — the remote VM's
disk is wiped on every disconnect, so nothing here persists except what's in the repo.

## 1. Clone the team repo

In [29]:
# Runs on the remote Colab VM (same whether you're on Colab web or the VS Code extension)
%cd /content
!git clone https://github.com/shaira-tahsin/CSE465-GainRAG.git
%cd /content/CSE465-GainRAG
!ls

/content
fatal: destination path 'CSE465-GainRAG' already exists and is not an empty directory.
/content/CSE465-GainRAG
 directory_listing.txt	 images     notebooks   requirements.txt
 GainRAG		'my data'   README.md   results

## 2. Install dependencies

In [2]:
!pip install -q -U transformers accelerate bitsandbytes datasets
!pip install -q pandas

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.6/11.6 MB 108.2 MB/s eta 0:00:0000:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 40.9/40.9 MB 18.7 MB/s eta 0:00:00:00:0100:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 555.1/555.1 kB 43.1 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.1/50.1 MB 13.8 MB/s eta 0:00:00:00:0100:01

## 3. Config — EDIT THIS CELL PER TEAMMATE / PER RUN

Everything you're likely to need to change lives here, in one place.

- `SHARD_FILE`: this teammate's dataset shard (after renaming — put your actual filename)
- `BACKEND`: `"local"` to run Llama-3-8B on this Colab T4, or `"craftx"` once the CraftX
  API key is available and confirmed to support logprobs (see CraftX section below —
  **do not switch to `"craftx"` until that's confirmed working**, it will silently
  produce wrong results if the API only returns generated text, not logprobs)
- `CRAFTX_API_KEY`: only needed if `BACKEND = "craftx"`. Loaded from Colab Secrets —
  **never hardcode the key directly in this cell or anywhere in this notebook.**

In [3]:
import os

# ---- EDIT THESE TWO LINES ----
SHARD_FILE = "/content/CSE465-GainRAG/my data/shard_1_shaira.jsonl"
BACKEND = "local"   # "local" or "craftx"
K_PASSAGES = 10
TASK = "HotpotQA"
ALPHA = 0.5
# --------------------------------

RESULTS_DIR = "/content/CSE465-GainRAG/results"
os.makedirs(RESULTS_DIR, exist_ok=True)
RESULTS_FILE = os.path.join(
    RESULTS_DIR,
    os.path.basename(SHARD_FILE).replace(".jsonl", "_results.jsonl")
)

# CraftX key — loaded from .env, not Colab Secrets (Secrets time out in VS Code)
CRAFTX_API_KEY = None
if BACKEND == "craftx":
    from dotenv import load_dotenv
    load_dotenv("/content/CSE465-GainRAG/.env", override=True)
    CRAFTX_API_KEY = os.environ.get("CRAFTX_API_KEY")
    assert CRAFTX_API_KEY, "CRAFTX_API_KEY not found — run the .env write cell first."

print(f"Shard: {SHARD_FILE}")
print(f"Backend: {BACKEND}")
print(f"Results will be saved to: {RESULTS_FILE}")

Shard: /content/CSE465-GainRAG/my data/shard_1_shaira.jsonl
Backend: local
Results will be saved to: /content/CSE465-GainRAG/results/shard_1_shaira_results.jsonl

## 4a. Load the model (local 4-bit) — skipped automatically if `BACKEND == "craftx"`

In [4]:
if BACKEND == "local":
    import torch
    from transformers import AutoTokenizer, AutoModelForCausalLM, BitsAndBytesConfig

    MODEL_ID = "NousResearch/Meta-Llama-3-8B-Instruct"  # ungated mirror
    LM_TYPE = "Llama-3-8B-Instruct"  # matches llm_prompts()'s expected model-type string

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=torch.float16,
        bnb_4bit_use_double_quant=True,
    )

    tokenizer = AutoTokenizer.from_pretrained(MODEL_ID)
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_ID,
        quantization_config=bnb_config,
        device_map="auto",
    )
    model.eval()  # frozen — no training, no_grad used below
    print("Local model loaded.")
else:
    print("BACKEND = craftx — skipping local model load.")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:138: UserWarning:
Error while fetching `HF_TOKEN` secret value from your vault: 'Requesting secret HF_TOKEN timed out. Secrets can only be fetched when running from the Colab UI.'.
  warnings.warn(f"\nError while fetching `HF_TOKEN` secret value from your vault: '{str(e)}'.")

config.json:   0%|          | 0.00/654 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/51.0k [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/73.0 [00:00<?, ?B/s]

model.safetensors.index.json:   0%|          | 0.00/23.9k [00:00<?, ?B/s]

Downloading bytes:           |  0.00B

Reconstructing (incomplete total...): |          |  0.00B /  0.00B

Fetching 4 files:   0%|          | 0/4 [00:00<?, ?it/s]

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/187 [00:00<?, ?B/s]

Local model loaded.

## 4b. CraftX API wrapper — EDIT ONCE KEY IS CONFIRMED TO SUPPORT LOGPROBS

**Status: unconfirmed.** Do not treat this cell as working until `test_craftx_logprobs()`
below has actually been run and shown real per-token logprob data in the response.

This is deliberately left as a stub with a clearly marked TODO — fill in the real request
shape once you get an answer from the CraftX developer (or test it yourself after buying
credits).

In [ ]:
if BACKEND == "craftx":
    import requests

    CRAFTX_ENDPOINT = "https://craftx.corecraftsolutions.com/v1/chat/completions"  # confirm exact path

    def test_craftx_logprobs():
        """Run this once, manually, before trusting BACKEND='craftx' for real results."""
        resp = requests.post(
            CRAFTX_ENDPOINT,
            headers={"Authorization": f"Bearer {CRAFTX_API_KEY}"},
            json={
                "model": "CraftX Meta Llama 3 8B Instruct",
                "messages": [{"role": "user", "content": "The capital of France is"}],
                "max_tokens": 5,
                "logprobs": True,       # TODO: confirm this param name is correct
                "top_logprobs": 1,      # TODO: confirm this param name is correct
                "echo": True,           # TODO: confirm CraftX supports echo mode at all
            },
        )
        print(resp.status_code)
        print(resp.json())
        return resp.json()

    # TODO: after confirming the shape above works, replace this with a real function that
    # returns teacher-forced logprobs for the gold answer tokens, with-context and without-context,
    # matching what ContrastiveTool.contrastive_PPL_multi_pro expects from the local path.
    def craftx_get_answer_logits(prompt, gold_answer):
        raise NotImplementedError(
            "Fill this in only after test_craftx_logprobs() confirms logprob support."
        )

    print("CraftX wrapper loaded — remember to run test_craftx_logprobs() before relying on it.")

## 5. Import the authors' gain-calculation code (unmodified)

If any of these imports fail, or the signatures below don't match, run the signature-check
cell right after this one and paste the output back before editing Step 6.

In [5]:
import sys
sys.path.insert(0, "/content/CSE465-GainRAG/GainRAG/gainRAG")

from llm_supervision.decoding import ContrastiveTool
from rag_workflow.prompts import get_input_with_R_Kth
from llm_inference.build_prompts import llm_prompts

contrastive_tool = ContrastiveTool()
print("Imports OK.")

Imports OK.

In [6]:
# Run this once to confirm exact argument names/order before trusting Step 6 below.
import inspect
print("get_input_with_R_Kth", inspect.signature(get_input_with_R_Kth))
print("contrastive_PPL_multi_pro", inspect.signature(ContrastiveTool.contrastive_PPL_multi_pro))

get_input_with_R_Kth (data_path, k=5, task='HotpotQA')
contrastive_PPL_multi_pro (self, model, tokenizer, query_prompt: str, query_prompt_w_contexts: List[str], gold_answer: str, alpha: float = 0.5) -> List[int]

## 6. Load this teammate's shard

In [7]:
import json

with open(SHARD_FILE) as f:
    questions = [json.loads(line) for line in f]

print(f"Loaded {len(questions)} questions from {SHARD_FILE}")
print(json.dumps(questions[0], indent=2)[:800])

Loaded 125 questions from /content/CSE465-GainRAG/my data/shard_1_shaira.jsonl
{
  "question_id": "5a713b325542994082a3e6b5",
  "question": "What was the capital of India when the Taj Mahal was commissioned?",
  "answers": [
    "Agra"
  ],
  "ctxs": [
    {
      "title": "Black Taj Mahal",
      "text": "The Black Taj Mahal (\"Black Taj\", \"Kaala Taj\", also \"the 2nd Taj\") is a legendary black marble mausoleum that is said to have been planned to be built across the Yamuna River opposite the Taj Mahal in Agra, Uttar Pradesh, India. Mughal emperor Shah Jahan is said to have desired a mausoleum for himself similar to that of the one he had built in memory of his third wife, Mumtaz Mahal.",
      "hasanswer": true,
      "is_supporting": false,
      "score": 0.0
    },
    {
      "title": "The Taj Mahal Palace Hotel",
      "text": "The Taj Mahal Palace Hotel (Ma

In [8]:
import json

with open(SHARD_FILE) as f:
    counts = [len(json.loads(line)["ctxs"]) for line in f]

print("Min:", min(counts))
print("Max:", max(counts))
print("Distribution:", sorted(set(counts)))
print("Questions with <10 ctxs:", sum(1 for c in counts if c < 10))

Min: 9
Max: 10
Distribution: [9, 10]
Questions with <10 ctxs: 2

## 7. Gain-calculation loop — with checkpointing

Safe to interrupt and re-run: already-completed `question_id`s are skipped, and every
result is written to disk immediately (not buffered), so a Colab disconnect loses at
most the one question in progress.

**Before running the full 125:** first run the smaller test cell right after this one
(first 5 questions only) to confirm everything works end-to-end and to get a rough
per-question timing estimate.

In [9]:
import json

FILTERED_SHARD_FILE = SHARD_FILE.replace(".jsonl", "_filtered.jsonl")

skipped = []
with open(SHARD_FILE) as f_in, open(FILTERED_SHARD_FILE, "w") as f_out:
    for line in f_in:
        q = json.loads(line)
        if len(q["ctxs"]) < K_PASSAGES:
            skipped.append(q["question_id"])
            continue
        f_out.write(line)

print(f"Skipped {len(skipped)} question(s) with fewer than {K_PASSAGES} passages: {skipped}")
print(f"Filtered shard saved to: {FILTERED_SHARD_FILE}")

Skipped 2 question(s) with fewer than 10 passages: ['5a79c7ac5542994bb9457097', '5a7cd66a554299452d57ba90']
Filtered shard saved to: /content/CSE465-GainRAG/my data/shard_1_shaira_filtered.jsonl

In [10]:
def run_gain_calc(shard_file, results_file, limit=None):
    with open(shard_file) as f:
        raw = [json.loads(line) for line in f]
    if limit:
        raw = raw[:limit]

    prompts_data = get_input_with_R_Kth(shard_file, k=K_PASSAGES, task=TASK)
    if limit:
        prompts_data = prompts_data[:limit]

    assert len(raw) == len(prompts_data), "Mismatch between raw shard and prompts_data length — check K_PASSAGES vs actual ctxs count."

    done_ids = set()
    if os.path.exists(results_file):
        with open(results_file) as f:
            for line in f:
                done_ids.add(json.loads(line)["question_id"])
        print(f"Resuming — {len(done_ids)} already done, skipping those.")

    with open(results_file, "a") as out_f:
        for i, (raw_q, item) in enumerate(zip(raw, prompts_data)):
            qid = raw_q["question_id"]
            if qid in done_ids:
                continue
            try:
                standard_query = llm_prompts(LM_TYPE, item["prompt_standard"], tokenizer, tokenize=False)[0]
                retrieved_prompts = [p["prompt_retrieved"] for p in item["passages"]]
                retrieved_queries = llm_prompts(LM_TYPE, retrieved_prompts, tokenizer, tokenize=False)

                gold_answers = list(set(item["answers"]))
                min_PPL_CD_list = [float("inf")] * len(item["passages"])
                for gold_answer in gold_answers:
                    if BACKEND == "local":
                        PPL_CD_list = contrastive_tool.contrastive_PPL_multi_pro(
                            model, tokenizer, standard_query, retrieved_queries, gold_answer, alpha=ALPHA
                        )
                    else:
                        PPL_CD_list = [craftx_get_answer_logits(p, gold_answer) for p in retrieved_queries]
                    min_PPL_CD_list = [min(a, b) for a, b in zip(min_PPL_CD_list, PPL_CD_list)]

                passages_out = []
                orig_ctxs = raw_q["ctxs"]  # same order as item["passages"] — both built from the same ctxs list
                for p, ppl, ctx in zip(item["passages"], min_PPL_CD_list, orig_ctxs):
                    passages_out.append({
                        "title": p["title"],
                        "text": p["text"],
                        "has_answer": p["has_answer"],
                        "is_supporting": ctx.get("is_supporting"),
                        "PPL_CD": float(ppl),
                    })

                record = {
                    "question_id": qid,
                    "question": item["question"],
                    "answers": item["answers"],
                    "passages": passages_out,
                }
                out_f.write(json.dumps(record) + "\n")
                out_f.flush()

                if (i + 1) % 10 == 0:
                    print(f"[{i+1}/{len(raw)}] done — last id: {qid}")

            except Exception as e:
                print(f"FAILED on {qid}: {e}")
                continue

    print(f"Done. Results in {results_file}")

In [11]:
# --- Small test run first: just the first 5 questions ---
TEST_RESULTS_FILE = RESULTS_FILE.replace(".jsonl", "_TEST5.jsonl")
run_gain_calc(FILTERED_SHARD_FILE, TEST_RESULTS_FILE, limit=5)

Done. Results in /content/CSE465-GainRAG/results/shard_1_shaira_results_TEST5.jsonl

In [12]:
# --- Once the test run above looks correct, run the full shard ---
run_gain_calc(FILTERED_SHARD_FILE, RESULTS_FILE)

[10/123] done — last id: 5a72a3c45542994cef4bc3ac
[20/123] done — last id: 5a738093554299623ed4abbb
[30/123] done — last id: 5a75092b55429916b0164242
[40/123] done — last id: 5a75e67f55429976ec32bc8b
[50/123] done — last id: 5a76f45a5542994aec3b719b
[60/123] done — last id: 5a77a7695542997042120ac4
[70/123] done — last id: 5a79caec5542994bb94570ad
[80/123] done — last id: 5a7af8fa55429927d897bf25
[90/123] done — last id: 5a7c6bcc55429935c91b519c
[100/123] done — last id: 5a7dbc175542995ed0d1666b
[110/123] done — last id: 5a7eec6f55429934daa2fc7c
[120/123] done — last id: 5a7fc8d05542992e7d278d86
Done. Results in /content/CSE465-GainRAG/results/shard_1_shaira_results.jsonl

## 8. Display results (for professor demo)

In [13]:
import pandas as pd

rows = []
with open(RESULTS_FILE) as f:
    for line in f:
        r = json.loads(line)
        best = min(r["passages"], key=lambda p: p.get("PPL_CD", float("inf")))
        rows.append({
            "question_id": r["question_id"],
            "question": r["question"][:80],
            "gold_answer": r["answers"][0],
            "best_passage_title": best["title"],
            "best_passage_gain_PPL_CD": round(best.get("PPL_CD", float("nan")), 3),
            "best_passage_is_supporting": best.get("is_supporting", None),
        })
pd.set_option('display.max_rows', None)
results_df = pd.DataFrame(rows)
results_df

,question_id,question,gold_answer,best_passage_title,best_passage_gain_PPL_CD,best_passage_is_supporting
0,5a713b325542994082a3e6b5,What was the capital of India when the Taj Mah...,Agra,Agra Fort,1.001000e+00,True
1,5a7140585542994082a3e6fa,Seal Harris was born in what county?,Polk County,"Cedartown, Georgia",1.015000e+00,True
2,5a71674f5542994082a3e819,When was the magazine Sam Duckworth got his na...,January 2004,Jason Perry (singer),7.333100e+01,False
3,5a716ec85542994082a3e82d,"Which movie was filmed first ""The Guest"" or ""Y...",You're Next,You're Next,1.893000e+00,True
4,5a7180205542994082a3e856,"The creator of ""Wallace and Gromit"" also creat...",Creature Comforts,Creature Comforts,1.049000e+00,True
5,5a722fae55429971e9dc9343,What is the name of the daughter of the Irish ...,Chloë Alexandra Adele Emily Agnew,Chloë Agnew,1.921000e+00,True
6,5a728f015542991f9a20c4e4,Which star of Zork was also the voice of Pac-Man?,Martin Ingerman,Marty Ingels,3.147000e+00,True
7,5a7299e75542991f9a20c524,"What movie was released at a later date, My Do...",Monsters vs. Aliens,Buchanan Brothers,1.001000e+00,False
8,5a72a0be5542992359bc3143,"This work of literature _______ , known by its...",Oedipus Rex,Dostoevsky and Parricide,1.002000e+00,True
9,5a72a3c45542994cef4bc3ac,"What is the birth name of the woman that ""A Wo...",Araminta Ross,Harriet Tubman,1.000000e+00,True
10,5a72f7df5542991f9a20c5d7,Piers Bizony has written articles for which ma...,BBC Focus,BBC Focus,1.001000e+00,True
11,5a7323ef5542994cef4bc477,Which battle took place first out of the Battl...,The Battle of Tarawa,Battle of Tarawa,1.237000e+00,True
12,5a733b835542991f9a20c6b2,Which movie is loosley based off the Brother G...,The Frog Prince,The Well of the World's End,2.900000e+00,False
13,5a7344e95542991f9a20c6ce,What song was number 4 on the charts when a so...,Rudebox,Rudebox (song),1.908000e+00,True
14,5a7351785542994cef4bc539,Was Atom Egoyans biggest commercial success on...,erotic thriller film,Chloe (film),1.416726e+03,True
15,5a73630655429901807db020,"Who was born first, Antonin Artaud or Elizabe...",Antonin Artaud,Theatre of Cruelty,1.000000e+00,False
16,5a73677455429901807db030,Of the companies that sponsor the British Leag...,Dunlop,British League Riders' Championship,1.000000e+00,True
17,5a736f7c5542991f29ee2e18,"Which legal, autonomous North American tribal ...",The Cherokee Nation,Cherokee Nation (1794–1907),1.055000e+00,True
18,5a737e4655429908901be2cc,This Fox News Specialist Host also took over w...,Cashin' In,Terry Keenan,1.633000e+00,False
19,5a738093554299623ed4abbb,Alex Haley wrote what novel about a man that w...,Roots: The Saga of an American Family,Roots: The Saga of an American Family,1.021000e+00,True
20,5a73977d554299623ed4ac08,What is the shared country of ancestry between...,Armenian,Art Laboe,2.557000e+00,True
21,5a73b8d655429908901be31f,"Which university is further North, University...",Stony Brook University,University of New Hampshire,1.045000e+00,True
22,5a746a4455429974ef308bf6,Which tennis player is older out of John Peers...,Simone Bolelli,2015 Trofeo Faip–Perrel – Singles,1.055000e+00,False
23,5a74af7e55429916b01641d2,"Who was born first, Johan Leysen or George Clo...",Johan Leysen,Johan Leysen,1.001000e+00,True
24,5a74b4dc55429979e2882a00,Which former lead guitarist has a solo album n...,Ted Nugent,Hunt Music,1.000000e+00,True
25,5a74f3f55542993748c8974b,"What movie was the actor born on May 4, 1946 i...",Five Summer Stories,Five Summer Stories,1.010000e+00,True
26,5a7503945542996c70cfae76,"Which Lithuanian-Canadian anthropologist, prim...",Birutė Marija Filomena Galdikas,Birutė Galdikas,1.525000e+00,True
27,5a7506f455429916b0164240,Connetquot High School is a public high schoo...,Oakdale,"Oakdale, New York",1.943000e+00,True
28,5a7509175542993748c897a3,What group of Elektra Records recording artist...,Saint Motel,Saint Motel,1.000000e+00,True
29,5a75092b55429916b0164242,What third film in a franchise did Camile Dela...,Transporter 3,Transporter 3,1.000000e+00,True
30,5a751bbe5542993748c897ba,Which 1962 film starring Tom Courtenay is base...,The Loneliness of the Long Distance Runner,The Loneliness of the Long Distance Runner (film),1.002000e+00,True
31,5a7525405542993748c897ce,"What is the name of the American author, songw...",James Weldon Johnson,James Weldon Johnson,1.000000e+00,True
32,5a7526945542993748c897d2,What year did the movement that Tess Asplund p...,2016,Nordic Resistance Movement,1.000000e+00,True
33,5a752fb75542993748c897df,What pop band features an Argentine actress th...,Erreway,Sweet Baby (Erreway song),1.000000e+00,True
34,5a75436155429974ef308cbc,The Pluralist school is said to have included ...,Leucippus,Pluralist school,1.000000e+00,True
35,5a75462d5542996c70cfaed3,"Who was born first, Kwok Kin Pong or Edison Chen?",Edison Koon-hei Chen,Edison Chen,4.249000e+00,True
36,5a75d45f5542994ccc918630,"Which refers to more breeds, Stabyhoun or Grif...",Griffon Bruxellois,Canine Chiari-like malformation,1.053000e+00,False
37,5a75da6d5542992db94736fa,The Declaration of Montreal was the founding d...,The 1st World Outgames,2006 World Outgames,1.572000e+00,True
38,5a75e06155429976ec32bc60,Who was the running mate of the man about whos...,Mike Pence,Insane Clown President,1.000000e+00,True
39,5a75e67f55429976ec32bc8b,Robert Jan van Pelt testified for the defense ...,David Irving,Robert Jan van Pelt,5.800000e+00,True
40,5a75fa8c55429976ec32bcda,Who composed music for this 1941 American anim...,Dan Crow,Dan Crow (musician),1.000000e+00,True
41,5a760ab65542994ccc918697,Alfred Balk served as the secretary of the Com...,Nelson Rockefeller,Nelson Rockefeller,1.001000e+00,True
42,5a7616755542992d0ec06028,Where is the county seat for people living in ...,"Gulfport, Biloxi","Henderson Point, Mississippi",3.175000e+00,True
43,5a7625e8554299109176e66a,In which year was the King who made the 1925 B...,1865,George V,1.000000e+00,True
44,5a76334c5542994ccc918710,Where is the author of Killing Pablo: The Hunt...,"St. Louis, Missouri",Mark Bowden,1.000000e+00,True
45,5a7634f155429976ec32bd6b,What shallow water table aquifer is located ne...,Ogallala Aquifer,Ogallala Aquifer,1.001000e+00,True
46,5a7652435542992d0ec060a5,Who was the first Russian composer to make a l...,Pyotr Ilyich Tchaikovsky,Swan Lake (1895),1.000000e+00,False
47,5a76641e5542992d0ec060d8,What American actress who died in 2011 starred...,Sada Thompson,Sada Thompson,1.005000e+00,True
48,5a76a8bb5542993569682c76,In what country did Gildo Siopaes win a bronze...,Austria,Jozef Golonka,1.008000e+00,False
49,5a76f45a5542994aec3b719b,What band formed in 1995 and came out with an ...,Fountains of Wayne,Jody Porter,1.000000e+00,False
50,5a77137455429972597f142a,"Who died more recently, Ferdinand Anton Ernst ...",Ferdinand Anton Ernst Porsche,Ferdinand Anton Ernst Porsche,1.007000e+00,True
51,5a771ead55429966f1a36c7c,Who starred as an American attorney in Grey Ga...,Ken Howard,Grey Gardens (2009 film),1.002000e+00,True
52,5a772c925542993735360208,Which was published first Polarity or The Farm...,The Farming Game,The Farming Game,1.000000e+00,True
53,5a77415b55429966f1a36cd2,What actor from Northern Ireland born in 1983 ...,"Martin ""Marty"" McCann",Martin McCann (actor),1.073000e+00,True
54,5a7758895542994aec3b729c,"Which American rock band, Sugar Ray or Agains...",rock,When It's Over (Sugar Ray song),3.334488e+08,False
55,5a77666555429966f1a36d1f,What is the nationality of the foreign born vi...,American,Oliver Fricker,2.805000e+00,True
56,5a77720255429967ab10517f,In what year did both Orson Scott Card's novel...,1985,Orson Scott Card bibliography,1.010000e+00,False
57,5a778b345542992a6e59decf,"Who was born first, Susan Oliver or W. S. Van ...",Woodbridge Strong Van Dyke II,W. S. Van Dyke,1.609000e+00,True
58,5a77984d5542992a6e59df14,What occupation do Henry Moore and John Wesley...,minister,Henry Moore (biographer),5.030400e+01,True
59,5a77a7695542997042120ac4,"Which documentary is the oldest, The Private L...",The Private Life of Plants,The Private Life of Plants,1.001000e+00,True
60,5a77a9df55429967ab10521c,What British novelist born in November 1898 wr...,Clive Staples Lewis,C. S. Lewis,1.126000e+00,True
61,5a77ad2f55429967ab105225,Sony/Philips Digital Interface Format can tran...,"TOSLINK (from ""Toshiba Link"") is a standardize...",TOSLINK,2.176000e+00,True
62,5a77c3d55542995d831812af,Who was the head of the Imperial Family that w...,Emperor of Japan,Masahiko Takeshita,1.588900e+01,True
63,5a77e70f5542992a6e59dfeb,What is the title of the 1979 film adaptation ...,The Tempest,The Tempest (1979 film),1.027000e+00,True
64,5a78abbc554299148911f90c,Which bi-weekly publication ranked Schreiber F...,Forbes ranked Schreiber Foods,Port Plaza Mall,7.266000e+00,False
65,5a78eff155429974737f790a,"What Happens in Vegas, an American comedy film...",2008,Lake Bell,1.001000e+00,True
66,5a79102a554299148911f9da,"This team which is moving from Oakland, Califo...","University of Nevada, Las Vegas",Señorita México,1.443000e+00,False
67,5a793bc95542994bb9456fc3,"Who was born first, Brooklyn Decker or Andy Ro...",Andrew Stephen Roddick,Andy Roddick,1.547900e+01,True
68,5a79c9c05542994bb94570a5,"This man who was born on April 25th, 1947, was...","Robert ""Bobby"" Bunda",Robert Bunda,7.210000e+00,True
69,5a79caec5542994bb94570ad,When was Leeds no longer called Elmet?,early 7th century,Elmet,3.158000e+00,True
70,5a7a030c5542996a35c17077,J.B. Scotts located on this 11 mile stretch in...,State Street,"Central Avenue (Albany, New York)",1.011000e+00,True
71,5a7a11c85542996a35c170b4,What is the English translation of the name of...,"""The Four Great Constables""",The Four (film),1.022000e+00,True
72,5a7a45425542990783324ee2,What American corporation owns Claim Jumper?,Landry's,"Landry's, Inc.",1.000000e+00,True
73,5a7a48c45542994f819ef1b7,With whom was a notable partner of Elena Kryka...,Oksana Grishuk,Oksana Grishuk,1.410000e+00,False
74,5a7a5b3a5542996c55b2dd71,What building is opposite the ceremonial meeti...,Mark Masons' Hall,"Mark Masons' Hall, London",2.586000e+00,True
75,5a7a77425542995eb53be83e,"Who has released more solo albums, Nick Carter...",Brady Seals,Thompson Street (album),1.006000e+00,False
76,5a7a954855429941d65f26cd,What album did John Lennon release before the ...,John Lennon/Plastic Ono Band,Imagine (John Lennon album),1.056000e+00,True
77,5a7aa07d55429941d65f2703,"Who directed the film in which Catherine Ann ""...",Robert Redford,The Horse Whisperer (film),1.005000e+00,True
78,5a7ae2f2554299042af8f6aa,Which sport has been played at the BayArena in...,football,BayArena,6.717693e+03,True
79,5a7af8fa55429927d897bf25,Consider the band formed in 2015 by JYP Entert...,13,Twicecoaster: Lane 2,1.472000e+00,True
80,5a7b1e22554299042af8f6e4,What award won by only twelve people has a man...,EGOT,Marvin Hamlisch,1.048000e+00,True
81,5a7b24fe55429931da12c9f7,Which dog breed has more derivative breeds fro...,German Spitz,Pomeranian (dog),1.558000e+00,False
82,5a7b43735542992d025e67cb,what type of media does Ratatouille and PlaySt...,video game,Ratatouille (video game),1.238600e+01,True
83,5a7b88b45542997c3ec97201,Which of Damon Stoudamire's cousins once playe...,Terrence Jones,Terrence Jones,1.000000e+00,True
84,5a7b89a3554299294a54a9e3,A Big Daddy is a fictional character in a seri...,25 million copies,BioShock (series),1.353000e+00,True
85,5a7ba8fc5542995eb53be986,"Who was born first, Umar Israilov or Ramzan Ka...",Ramzan Kadyrov,Ramzan Kadyrov,1.000000e+00,True
86,5a7bb7f2554299042af8f7b6,"What Cantonese slang term can mean both ""ghost...",Gweilo,Gweilo,1.005000e+00,True
87,5a7c17c95542990527d5544d,A guitar player called Noodles is a longtime m...,The Offspring,The Offspring,1.000000e+00,True
88,5a7c49dc55429935c91b514f,The head of the Foreign Relations Department o...,Engineering,Hari Bahadur Basnet,1.002000e+00,True
89,5a7c6bcc55429935c91b519c,Rock Springs is a collection of short stories ...,1944,Richard Ford,5.104000e+00,True
90,5a7c6c9d554299683c1c6302,In what county was Duffy Jackson born?,Nassau County,Duffy Jackson,1.144000e+00,True
91,5a7c8e7955429935c91b521a,Back Home is a children's historical novel ada...,Hayley Catherine Rose Vivien Mills,Hayley Mills,4.291000e+00,True
92,5a7c9d2e55429935c91b5261,What legend that lends its name to a modern me...,Wendigo,Wendigo,1.001000e+00,True
93,5a7ca98f55429935c91b5288,What religion was the martyr to whom the Lady ...,Christian,Saint George,1.002000e+00,True
94,5a7ce50f55429909bec76869,In what year did the Danish plant ecologist wh...,1974,Carsten Olsen,1.136000e+00,True
95,5a7cf59b55429909bec768c7,Who was born first Burton Cummings or Sharlee...,Burton Lorne Cummings,Burton Cummings,1.415700e+01,True
96,5a7cfea2554299452d57babe,"Which aired first, Life After People or Werner...",Werner Herzog Eats His Shoe,Werner Herzog Eats His Shoe,1.001000e+00,True
97,5a7db62d5542997cc2c4747c,What German state was Karl Julius Perleb born in?,Baden-Württemberg,Freiburg im Breisgau,1.015000e+00,True
98,5a7dbb295542990b8f503a4b,"Which Russian professional ice hockey player, ...",Pavel Valerievich Datsyuk,Pavel Datsyuk,2.682000e+00,True
99,5a7dbc175542995ed0d1666b,What russian Marxist revolutionary born in 187...,Anatoly Vasilyevich Lunacharsky,Anatoly Lunacharsky,2.268000e+00,True
100,5a7e1cad55429965cec5ea75,Was Pocahontas made before Born in China?,yes,Born in China,4.963741e+04,True
101,5a7e32905542991319bc943b,Jennifer Jones captained the gold medalists fo...,Curling,Sochi bid for the 2014 Winter Olympics,1.000000e+00,False
102,5a7e3b585542995ed0d166df,"Which film was released first, Home on the Ran...",Home on the Range,Pete's Dragon (2016 film),1.997000e+00,True
103,5a7e4af3554299495941998c,The founder of the Ali Akbar College of Music ...,the sarod,Ali Akbar Khan,2.579300e+01,True
104,5a7e6f295542991319bc94b1,Who gave the mother of Alberic II of Spoleto t...,Pope John X,Marozia,1.000000e+00,True
105,5a7e86245542991319bc94ce,Who was the New York City Fire Commissioner at...,Rhinelander Waldo,Rhinelander Waldo,1.000000e+00,True
106,5a7e910a554299306751357f,Who was the artist that recorded a duet in 198...,Gary Morris,Makin' Up for Lost Time (The Dallas Lovers' Song),5.158000e+00,True
107,5a7eacd855429930675135c3,What is the nationality of the actor who was a...,American,Charles Bronson,1.000000e+00,True
108,5a7eb22655429930675135cb,Which current CBS NBA analyst played for the P...,Greg Anthony,1998–99 Portland Trail Blazers season,1.000000e+00,True
109,5a7eec6f55429934daa2fc7c,The Hindmarsh Stadium is sponsored by a brewer...,69.7 million litres,Coopers Brewery,1.138000e+00,True
110,5a7f296f55429934daa2fd10,Live Wire Radio will possibly be considered as...,1974,A Prairie Home Companion,1.001000e+00,True
111,5a7f38e255429930675136b6,The Ronkonkama railroad station and the town o...,Long Island,"Ronkonkoma, New York",9.644000e+00,True
112,5a7f40055542992e7d278cc0,What did an English former footballer purchas...,50 JJB Sports Fitness Clubs,DW Sports Fitness,1.598000e+00,True
113,5a7f48e15542992e7d278ce6,Brad Elterman is a professional photographer w...,its eclectic mix of musical styles,Blondie (band),1.171600e+01,True
114,5a7f6fd75542992e7d278cfa,Which Canadian rock band released a song calle...,Rush,Nobody's Hero,1.000000e+00,True
115,5a7f7c285542994857a76746,California joined the Union due to the passage...,five,Compromise of 1850,5.633100e+01,True
116,5a7fa0d55542995d8a8dded3,What professional do both Marc Bolan and Ian M...,musician,Marc Bolan,3.260700e+01,True
117,5a7fa55555429969796c1b0e,"The star of ""The Inkwell"" also starred in what...",Menace II Society,Streiht Up Menace,1.005000e+00,False
118,5a7fb1765542992e7d278d20,Why does the City of Boston get their christma...,for their assistance after the 1917 Halifax Ex...,Boston Christmas Tree,4.335000e+00,True
119,5a7fc8d05542992e7d278d86,Which Air Force member was behind enemy lines ...,"Lieutenant Colonel Iceal E. ""Gene"" Hambleton",Iceal Hambleton,1.385000e+00,True
120,5a8010685542992bc0c4a69a,Jimmy Garcia lost by unanimous decision to a p...,WBO lightweight title,Genaro Hernández,8.320000e+00,True
121,5a801f215542992bc0c4a6b2,the first woman to be the chef de mission of a...,2002 Winter Olympics,Alisa Camplin,4.002000e+00,True
122,5a8051265542992bc0c4a6f8,Tommy Swerdlow co-wrote the screenplay of what...,Cool Runnings,Cool Runnings,1.000000e+00,True

In [14]:
csv_rows = []
with open(RESULTS_FILE) as f:
    for line in f:
        r = json.loads(line)
        best = min(r["passages"], key=lambda p: p.get("PPL_CD", float("inf")))
        csv_rows.append({
            "question_id": r["question_id"],
            "question": r["question"],  # full text, untruncated
            "gold_answer": r["answers"][0],
            "best_passage_title": best["title"],
            "best_passage_gain_PPL_CD": round(best.get("PPL_CD", float("nan")), 3),
            "best_passage_is_supporting": best.get("is_supporting", None),
        })

csv_df = pd.DataFrame(csv_rows)
csv_df.to_csv(os.path.join(RESULTS_DIR, "results_table.csv"), index=False)
print(f"Saved: {RESULTS_DIR}/results_table.csv")

Saved: /content/CSE465-GainRAG/results/results_table.csv

In [15]:
# Full detail for one example question — mirrors the Phase 1 single-example table,
# useful for walking the professor through one worked example live.
example = json.loads(open(RESULTS_FILE).readline())
detail_df = pd.DataFrame([
    {"title": p["title"], "is_supporting": p.get("is_supporting"), "gain_PPL_CD": round(p.get("PPL_CD", float("nan")), 3)}
    for p in example["passages"]
]).sort_values("gain_PPL_CD")

print("Question:", example["question"])
print("Gold answer:", example["answers"][0])
detail_df

Question: What was the capital of India when the Taj Mahal was commissioned?
Gold answer: Agra

                        title  is_supporting  gain_PPL_CD
8                   Agra Fort           True        1.001
0             Black Taj Mahal          False        1.009
6       Taj Mahal (1963 film)          False        1.042
9                   Taj Mahal           True        1.097
4        Taj Mahal Bangladesh          False        1.611
7                Kester Smith          False        1.723
1  The Taj Mahal Palace Hotel          False        2.156
2           Taj corridor case          False        2.704
3     Taj Mahal, Bulandshahar          False       15.585
5                  R. Chandru          False       29.888

## 9. Record summary (for the writeup / professor demo)

A small human-readable log of this run — what shard, how many questions, how many
succeeded/failed, and the `is_supporting` sanity check (does the gain-selected top
passage actually match a real supporting fact more often than chance?).

In [16]:
total = len(results_df)
supporting_match_rate = results_df["best_passage_is_supporting"].mean() if total else float("nan")

summary = {
    "shard_file": SHARD_FILE,
    "backend": BACKEND,
    "questions_processed": total,
    "gain_top_pick_matches_supporting_fact_rate": round(float(supporting_match_rate), 4) if total else None,
}
print(json.dumps(summary, indent=2))

with open(os.path.join(RESULTS_DIR, "run_summary.json"), "w") as f:
    json.dump(summary, f, indent=2)

{
  "shard_file": "/content/CSE465-GainRAG/my data/shard_1_shaira.jsonl",
  "backend": "local",
  "questions_processed": 123,
  "gain_top_pick_matches_supporting_fact_rate": 0.8455
}

## 10. Push results back to the team repo

Run this from a terminal cell — commits just the results + summary, not model weights
or caches (already excluded via `.gitignore`).

In [33]:
!git config --global user.email "shaira.the.tahsin@gmail.com"
!git config --global user.name "Shaira Tahsin"

from getpass import getpass
token = getpass('Enter your GitHub PAT: ')
username = "shaira-tahsin"

!git remote set-url origin https://{username}:{token}@github.com/your-username/CSE465-GainRAG.git

In [34]:
%cd /content/CSE465-GainRAG
!git add results/
!git commit -m "Add gain-calc results for shard: {SHARD_FILE}"
!git push

/content/CSE465-GainRAG
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	my data/shard_1_shaira_filtered.jsonl

nothing added to commit but untracked files present (use "git add" to track)
remote: Repository not found.
fatal: repository 'https://github.com/your-username/CSE465-GainRAG.git/' not found

## 11. Generate answers from the best passage + score EM/F1 (this teammate's shard)

Everything so far computes **gain scores** (which passage the model would benefit from
most) but stops short of actually answering the question — this section closes that gap
so results are comparable to the paper's Table 1 (HotpotQA columns).

Reuses the authors' own evaluation code unmodified:
- `em_max_over_ground_truths` / `f1_max_over_ground_truths` from `evaluation/evaluation.py`
  — same SQuAD-style normalization (lowercase, strip punctuation/articles) and
  max-over-multiple-gold-answers logic the paper itself uses
- `llm_response` from `llm_inference/inference_hf.py` — same greedy decoding
  (`do_sample=False`, `num_beams=1`, `max_new_tokens=512`) the authors use for generation

For each question: take the passage with the **lowest PPL_CD** (the gain-score winner),
build a prompt from question + that passage, generate an answer, score it against the
gold answer(s).

In [19]:
from evaluation.evaluation import em_max_over_ground_truths, f1_max_over_ground_truths
from llm_inference.inference_hf import llm_response

print("Evaluation + generation functions imported.")

Evaluation + generation functions imported.

In [20]:
def run_generate_and_score(shard_file, results_file, scored_file, limit=None):
    with open(results_file) as f:
        results = [json.loads(line) for line in f]
    if limit:
        results = results[:limit]

    # Rebuild prompts_data (cheap — no model calls) to recover prompt_retrieved strings,
    # which weren\'t kept in the gain-calc output.
    with open(shard_file) as f:
        raw = [json.loads(line) for line in f]
    id_to_raw_index = {q["question_id"]: i for i, q in enumerate(raw)}

    prompts_data = get_input_with_R_Kth(shard_file, k=K_PASSAGES, task=TASK)

    done_ids = set()
    if os.path.exists(scored_file):
        with open(scored_file) as f:
            for line in f:
                done_ids.add(json.loads(line)["question_id"])
        print(f"Resuming — {len(done_ids)} already scored, skipping.")

    with open(scored_file, "a") as out_f:
        for i, r in enumerate(results):
            qid = r["question_id"]
            if qid in done_ids:
                continue
            try:
                raw_idx = id_to_raw_index[qid]
                item = prompts_data[raw_idx]

                # Index of the passage with the lowest (best) gain score
                best_idx = min(range(len(r["passages"])), key=lambda j: r["passages"][j].get("PPL_CD", float("inf")))
                best_prompt_retrieved = item["passages"][best_idx]["prompt_retrieved"]

                wrapped_prompt = llm_prompts(LM_TYPE, best_prompt_retrieved, tokenizer, tokenize=False)[0]
                inputs = tokenizer(wrapped_prompt, return_tensors="pt").to(model.device)
                predicted_answer = llm_response(inputs, model, tokenizer)[0]

                em = em_max_over_ground_truths(predicted_answer, r["answers"], regex=True)
                f1 = f1_max_over_ground_truths(predicted_answer, r["answers"])

                out_record = {
                    "question_id": qid,
                    "question": r["question"],
                    "gold_answers": r["answers"],
                    "best_passage_title": r["passages"][best_idx]["title"],
                    "predicted_answer": predicted_answer,
                    "em": int(bool(em)),
                    "f1": float(f1),
                }
                out_f.write(json.dumps(out_record) + "\n")
                out_f.flush()

                if (i + 1) % 10 == 0:
                    print(f"[{i+1}/{len(results)}] scored — last id: {qid}")

            except Exception as e:
                print(f"FAILED scoring {qid}: {e}")
                continue

    print(f"Done scoring. Results in {scored_file}")

In [21]:
# --- Small test first: just 5 questions ---
SCORED_FILE = RESULTS_FILE.replace("_results.jsonl", "_scored.jsonl")
TEST_SCORED_FILE = SCORED_FILE.replace(".jsonl", "_TEST5.jsonl")
TEST_RESULTS_FILE_FOR_SCORING = RESULTS_FILE.replace(".jsonl", "_TEST5.jsonl")  # from Section 7's test run

run_generate_and_score(FILTERED_SHARD_FILE, TEST_RESULTS_FILE_FOR_SCORING, TEST_SCORED_FILE, limit=5)

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Ignoring clean_up_tokenization_spaces=True for BPE tokenizer TokenizersBackend. The clean_up_tokenization post-processing step is designed for WordPiece tokenizers and is destructive for BPE (it strips spaces before punctuation). Set clean_up_tokenization_spaces=False to suppress this warning, or set clean_up_tokenization_spaces_for_bpe_even_though_it_will_corrupt_output=True to force cleanup anyway.
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Done scoring. Results in /content/CSE465-GainRAG/results/shard_1_shaira_scored_TEST5.jsonl

In [22]:
# --- Once the test looks correct, score the full shard ---
run_generate_and_score(FILTERED_SHARD_FILE, RESULTS_FILE, SCORED_FILE)

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[10/123] scored — last id: 5a72a3c45542994cef4bc3ac

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[20/123] scored — last id: 5a738093554299623ed4abbb

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[30/123] scored — last id: 5a75092b55429916b0164242

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[40/123] scored — last id: 5a75e67f55429976ec32bc8b

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[50/123] scored — last id: 5a76f45a5542994aec3b719b

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[60/123] scored — last id: 5a77a7695542997042120ac4

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[70/123] scored — last id: 5a79caec5542994bb94570ad

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[80/123] scored — last id: 5a7af8fa55429927d897bf25

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[90/123] scored — last id: 5a7c6bcc55429935c91b519c

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[100/123] scored — last id: 5a7dbc175542995ed0d1666b

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[110/123] scored — last id: 5a7eec6f55429934daa2fc7c

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

[120/123] scored — last id: 5a7fc8d05542992e7d278d86

[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)
[transformers] Both `max_new_tokens` (=512) and `max_length`(=4096) seem to have been set. `max_new_tokens` will take precedence. Please refer to the documentation for more information. (https://huggingface.co/docs/transformers/main/en/main_classes/text_generation)

Done scoring. Results in /content/CSE465-GainRAG/results/shard_1_shaira_scored.jsonl

### This teammate's EM/F1 summary

In [23]:
scored_rows = []
with open(SCORED_FILE) as f:
    for line in f:
        scored_rows.append(json.loads(line))

scored_df = pd.DataFrame(scored_rows)
avg_em = scored_df["em"].mean() * 100
avg_f1 = scored_df["f1"].mean() * 100
avg_avg = (avg_em + avg_f1) / 2

print(f"Questions scored: {len(scored_df)}")
print(f"EM:  {avg_em:.2f}")
print(f"F1:  {avg_f1:.2f}")
print(f"Avg: {avg_avg:.2f}")

scored_df.to_csv(os.path.join(RESULTS_DIR, "scored_table.csv"), index=False)
scored_df.head(10)

Questions scored: 123
EM:  69.11
F1:  71.16
Avg: 70.13

,question_id,question,gold_answers,best_passage_title,predicted_answer,em,f1
0,5a713b325542994082a3e6b5,What was the capital of India when the Taj Mah...,[Agra],Agra Fort,Agra.,1,1.000000
1,5a7140585542994082a3e6fa,Seal Harris was born in what county?,[Polk County],"Cedartown, Georgia",Polk County.,1,1.000000
2,5a71674f5542994082a3e819,When was the magazine Sam Duckworth got his na...,[January 2004],Jason Perry (singer),Sam Duckworth got his name Get Cape. Wear Cape...,0,0.000000
3,5a716ec85542994082a3e82d,"Which movie was filmed first ""The Guest"" or ""Y...",[You're Next],You're Next,"""You're Next"" (2011)",1,0.800000
4,5a7180205542994082a3e856,"The creator of ""Wallace and Gromit"" also creat...",[Creature Comforts],Creature Comforts,Creature Comforts.,1,1.000000
5,5a722fae55429971e9dc9343,What is the name of the daughter of the Irish ...,[Chloë Alexandra Adele Emily Agnew],Chloë Agnew,Chloë Agnew.,0,0.571429
6,5a728f015542991f9a20c4e4,Which star of Zork was also the voice of Pac-Man?,[Martin Ingerman],Marty Ingels,Marty Ingels.,0,0.000000
7,5a7299e75542991f9a20c524,"What movie was released at a later date, My Do...",[Monsters vs. Aliens],Buchanan Brothers,Monsters vs. Aliens.,1,1.000000
8,5a72a0be5542992359bc3143,"This work of literature _______ , known by its...",[Oedipus Rex],Dostoevsky and Parricide,Oedipus Rex.,1,1.000000
9,5a72a3c45542994cef4bc3ac,"What is the birth name of the woman that ""A Wo...",[Araminta Ross],Harriet Tubman,Araminta Ross.,1,1.000000

## 12. Push scored results to the team repo

In [27]:
username = "shaira-tahsin"
!git remote set-url origin https://{username}:{token}@github.com/shaira-tahsin/CSE465-GainRAG.git

In [28]:
%cd /content/CSE465-GainRAG
!git add results/
!git commit -m "Add answer generation + EM/F1 scoring for shard"
!git push

/content/CSE465-GainRAG
On branch main
Your branch is ahead of 'origin/main' by 1 commit.
  (use "git push" to publish your local commits)

Untracked files:
  (use "git add <file>..." to include in what will be committed)
	my data/shard_1_shaira_filtered.jsonl

nothing added to commit but untracked files present (use "git add" to track)
remote: Permission to shaira-tahsin/CSE465-GainRAG.git denied to shaira-tahsin.
fatal: unable to access 'https://github.com/shaira-tahsin/CSE465-GainRAG.git/': The requested URL returned error: 403

## 13. Merge all four teammates' shards into one final table

Run this once everyone has pushed their own `*_scored.jsonl` — pulls everyone's results,
combines all ~500 questions, and computes the same EM/F1/Avg metrics as the paper's
Table 1 so you can compare directly.

**Reference — paper's Table 1, HotpotQA columns (Jiang et al., 2025):**

| Method | EM | F1 | Avg |
|---|---|---|---|
| Naive (no retrieval) | 22.40 | 22.44 | 22.42 |
| Standard RAG | 31.80 | 33.23 | 32.51 |
| Rerank | 35.80 | 37.45 | 36.62 |
| **GainRAG** | **39.60** | **41.99** | **40.79** |

Your pipeline is closest in spirit to the GainRAG row (gain-score-based passage
selection), but isn't identical — no trained selector model, argmax-over-gain-scores
instead, and a 4-bit quantized model instead of full precision. Worth stating this
plainly in the writeup: this is a **directional** reproduction of the mechanism, not a
strict replication of their exact pipeline.

In [ ]:
%cd /content/CSE465-GainRAG
!git pull

In [ ]:
import glob

all_scored = []
for fpath in glob.glob(os.path.join(RESULTS_DIR, "*_scored.jsonl")):
    if "TEST5" in fpath:
        continue
    with open(fpath) as f:
        for line in f:
            all_scored.append(json.loads(line))

print(f"Combined {len(all_scored)} questions across all shards (target: 500, or fewer if some questions were filtered out per shard).")

In [ ]:
final_df = pd.DataFrame(all_scored)

final_em = final_df["em"].mean() * 100
final_f1 = final_df["f1"].mean() * 100
final_avg = (final_em + final_f1) / 2

comparison = pd.DataFrame([
    {"Method": "Naive (paper)", "EM": 22.40, "F1": 22.44, "Avg": 22.42},
    {"Method": "Standard RAG (paper)", "EM": 31.80, "F1": 33.23, "Avg": 32.51},
    {"Method": "Rerank (paper)", "EM": 35.80, "F1": 37.45, "Avg": 36.62},
    {"Method": "GainRAG (paper)", "EM": 39.60, "F1": 41.99, "Avg": 40.79},
    {"Method": "Our reproduction", "EM": round(final_em, 2), "F1": round(final_f1, 2), "Avg": round(final_avg, 2)},
])
comparison

In [ ]:
final_df.to_csv(os.path.join(RESULTS_DIR, "final_combined_results.csv"), index=False)
comparison.to_csv(os.path.join(RESULTS_DIR, "final_comparison_table.csv"), index=False)
print("Saved: final_combined_results.csv and final_comparison_table.csv")